### ISSUE TITLE
关于使用自己的数据集训练CRNN网络的疑问

### ISSUE THREAD

**Issue by Slimoun** [jasnei/ctpn-crnn-pytorch#1]
我用的是icdar2017rctw数据集，我自己将数据集分成了训练集和测试集，也按照你给的提示把train_own和test_own放到了dataset/txt文件夹下。但是训练过程中总是出现loss变成NaN的情况。有什么办法吗？更改了lr也还是出现这种情况。我用你给的数据集感觉是可以正常训练的，虽然没有训练完。是否对alphabets也有要求？alphabet我换成了我用的数据集中所出现的字符。求帮助！！！
数据集：https://pan.baidu.com/s/10yddpEgnVnAIZF9XnYuadg
提取码：e5ag

**Comment by jasnei** [comment]
你好，
可以尝试把batchsize 改写一点，如8， 16， 32
可以尝试把lr改小点，如：1e-4, 1e-5
